import "~/styles/globals.css";

import { type Metadata } from "next";
import localfont from "next/font/local";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const hitchcut = localfont({
  src: "../fonts/Hitchcut-Regular.otf",
  variable: "--font-hitchcut",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={hitchcut.variable}>
      <body>{children}</body>
    </html>
  );
}
